
name: CI

on:

  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world
      - name: Azure Login
        uses: azure/login@v1
        
        with:
          
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show 
      - uses: hashicorp/setup-terraform@v3
        # env:
        #  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
        #  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      - name: Terraform Init
        # run: terraform init
        env:
         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
        

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main'
        env:
         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve
